version: "3.7"


services:
  usb-mysql:
    image: mysql:latest
    volumes:
      - /home/alzo/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
    networks:
      - usb-bridge
    ports:
      - 3306:3306

  backend:
    build: backend/
    environment:
      FLASK_APP: backend.py
      UPLOAD_FOLDER: /tmp_upload
      SECRET_KEY: 
      DATABASE_URL: 
    volumes:
      - /mnt/e/usbreg/tmp_upload:/tmp_upload
    ports:
      - 4000:4000
    depends_on:
      - usb-mysql
    networks:
      - usb-bridge

  frontend:
    build: frontend/
    environment:
      FLASK_APP: frontend.py
      UPLOAD_FOLDER: /tmp_upload
      SECRET_KEY: 
      BACKEND_ADDRESS: http://backend:4000
    volumes:
      - /mnt/e/usbreg/tmp_upload:/tmp_upload
    ports:
      - 8080:3000
    depends_on:
      - backend
    networks:
      - usb-bridge

networks:
  usb-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24


