"""add indexing

Revision ID: 18b3e1650c1d
Revises: 27214d357fe6
Create Date: 2022-06-07 08:48:43.335167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b3e1650c1d'
down_revision = '27214d357fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='department')
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)
    op.create_index(op.f('ix_devinfo_department_id'), 'devinfo', ['department_id'], unique=False)
    op.create_index(op.f('ix_devinfo_dev_numb'), 'devinfo', ['dev_numb'], unique=False)
    op.create_index(op.f('ix_devinfo_rec_date'), 'devinfo', ['rec_date'], unique=False)
    op.create_index(op.f('ix_devinfo_status'), 'devinfo', ['status'], unique=False)
    op.create_index(op.f('ix_permit_computer_comp_name'), 'permit_computer', ['comp_name'], unique=False)
    op.create_index(op.f('ix_permit_computer_rec_date'), 'permit_computer', ['rec_date'], unique=False)
    op.create_index(op.f('ix_permit_computer_status'), 'permit_computer', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permit_computer_status'), table_name='permit_computer')
    op.drop_index(op.f('ix_permit_computer_rec_date'), table_name='permit_computer')
    op.drop_index(op.f('ix_permit_computer_comp_name'), table_name='permit_computer')
    op.drop_index(op.f('ix_devinfo_status'), table_name='devinfo')
    op.drop_index(op.f('ix_devinfo_rec_date'), table_name='devinfo')
    op.drop_index(op.f('ix_devinfo_dev_numb'), table_name='devinfo')
    op.drop_index(op.f('ix_devinfo_department_id'), table_name='devinfo')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.create_index('name', 'department', ['name'], unique=False)
    # ### end Alembic commands ###
