"""My tables

Revision ID: 27214d357fe6
Revises: 2e1b2314fd6a
Create Date: 2022-06-06 21:42:43.141143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27214d357fe6'
down_revision = '2e1b2314fd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('doc_administrator', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permit_computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_name', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('last_state', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('rec_date', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_numb', sa.String(length=20), nullable=False),
    sa.Column('dev_id', sa.String(length=150), nullable=False),
    sa.Column('dev_type', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('doc_numb', sa.String(length=200), nullable=True),
    sa.Column('doc_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('rec_date', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('last_state', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('fullname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'department_id')
    op.drop_column('user', 'fullname')
    op.drop_table('devinfo')
    op.drop_table('permit_computer')
    op.drop_table('department')
    # ### end Alembic commands ###
