"""Add all tables

Revision ID: 94c23e1ddd93
Revises: 
Create Date: 2023-01-04 18:11:38.287938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c23e1ddd93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('doc_administrator', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)
    op.create_table('permit_computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_name', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('last_state', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('rec_date', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_computer_comp_name'), 'permit_computer', ['comp_name'], unique=False)
    op.create_index(op.f('ix_permit_computer_rec_date'), 'permit_computer', ['rec_date'], unique=False)
    op.create_index(op.f('ix_permit_computer_status'), 'permit_computer', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('devinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_numb', sa.String(length=20), nullable=False),
    sa.Column('dev_id', sa.String(length=150), nullable=False),
    sa.Column('dev_type', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('doc_numb', sa.String(length=200), nullable=True),
    sa.Column('doc_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('rec_date', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('last_state', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devinfo_department_id'), 'devinfo', ['department_id'], unique=False)
    op.create_index(op.f('ix_devinfo_dev_numb'), 'devinfo', ['dev_numb'], unique=False)
    op.create_index(op.f('ix_devinfo_rec_date'), 'devinfo', ['rec_date'], unique=False)
    op.create_index(op.f('ix_devinfo_status'), 'devinfo', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devinfo_status'), table_name='devinfo')
    op.drop_index(op.f('ix_devinfo_rec_date'), table_name='devinfo')
    op.drop_index(op.f('ix_devinfo_dev_numb'), table_name='devinfo')
    op.drop_index(op.f('ix_devinfo_department_id'), table_name='devinfo')
    op.drop_table('devinfo')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_permit_computer_status'), table_name='permit_computer')
    op.drop_index(op.f('ix_permit_computer_rec_date'), table_name='permit_computer')
    op.drop_index(op.f('ix_permit_computer_comp_name'), table_name='permit_computer')
    op.drop_table('permit_computer')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
